name: build

on:
  push:
    paths:
      - 'src/**.py'
      - 'tests/**.py'
      - '.github/workflows/build.yml'
      - 'poetry.lock'
    branches: [ master ]
  pull_request:
    paths:
      - 'src/**.py'
      - 'tests/**.py'
      - '.github/workflows/build.yml'
      - 'poetry.lock'
    branches: [ master ]
  workflow_run:
    workflows:
      - 'pre-commit.ci'
    types:
      - completed

jobs:

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11-dev' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - name: Run tests
        run: poetry run pytest --cov=src --cov-report=xml
      - name: Upload Coverage Report to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
      - name: Build
        run: poetry build
